### ISSUE TITLE
[Suggestion] Add support for Large Fluid Cells (Steel, Aluminium, etc.) for recognizing fluid quantities within your inventory for recipes.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/JustEnoughCalculation#10]
Self explanatory suggestion (also thank you for opening up this issue page), right now if you have one of the aforementioned cells in your inventory, the fluids stored do not count as part of your current inventory for recipe cost calculations. Would be a great for this to be fixed.

Thanks!

**Comment by mainrs** [comment]
~~I've almost implemented this, but I have issues with adding a dependency to the GT API (it makes checking for the cell fluid easier via `GTUtility` class). The project already has `com.github.GTNewHorizons:GT5-Unofficial:5.09.48.133:dev` as a compile only dependency, but I am unsure how to add the API jar file to it.~~ Looks like my Gradle project was just not correctly imported. I cleared the cache and it works now. The class is also named `GT_Utility`.

Additionally, I had trouble setting up a client that contained GT. Mostly due to transitive dependencies to other mods. Is there a list of mods I need for a minimal environment that contains GT so I can check my implementation?

**Comment by PlayfulPiano** [comment]
> ~I've almost implemented this, but I have issues with adding a dependency to the GT API (it makes checking for the cell fluid easier via `GTUtility` class). The project already has `com.github.GTNewHorizons:GT5-Unofficial:5.09.48.133:dev` as a compile only dependency, but I am unsure how to add the API jar file to it.~ Looks like my Gradle project was just not correctly imported. I cleared the cache and it works now. The class is also named `GT_Utility`.
> 
> Additionally, I had trouble setting up a client that contained GT. Mostly due to transitive dependencies to other mods. Is there a list of mods I need for a minimal environment that contains GT so I can check my implementation?

Your best bet would probably be the info in the GT-New-Horizons-Modpack repo or the nightly builds that get posted in the discord.

**Comment by PlayfulPiano** [comment]
Also the discord has a #mod-dev channel for other development related questions if you need to find out about anything.
